export enum bdErrors {
  'ERROR_GET_ALL' = 'ERROR_GET_ALL',
  'ERROR_GET' = 'ERROR_GET',
  'ERROR_UPDATE' = 'ERROR_UPDATE',
  'ERROR_INSERT' = 'ERROR_INSERT',
  'ERROR_ELIMINAR' = 'ERROR_ELIMINAR',
  'ERROR_DECRYPT_PASS' = 'ERROR_DECRYPT_PASS',
  'ERROR_ENCRYPT_PASS' = 'ERROR_ENCRYPT_PASS',
  'ERROR_POST_LOGIN' = 'ERROR_POST_LOGIN'
}